Repository openshift-knative/docs, pull requests merged in 2019-10, with the labels that each got.

#20 Updates to remove Serving
  404.html
  docs/con_knative-operators.html
  docs/con_knative-v071.html
  docs/index.html
  docs/proc_apache-camel.html
  docs/proc_apache-kafka.html
  docs/proc_knative-eventing-v071.html
  docs/proc_knative-eventing.html
  local-site.yml
  modules/ROOT/nav.adoc
  modules/ROOT/pages/con_knative-operators.adoc
  modules/ROOT/pages/con_knative-v071.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/proc_apache-camel.adoc
  modules/ROOT/pages/proc_apache-kafka.adoc
  modules/ROOT/pages/proc_knative-eventing.adoc
  modules/ROOT/pages/proc_knative-serving-v071.adoc
  sitemap.xml
Labels: size/XL

#21 Updated readme
  README.md
  contributing/con_contributing-documentation.md
Labels: size/M

#23 Updating Image for Kafka default channel
  docs/_images/kafka-configmap.png
Labels: size/XS
