Repository openshift-knative/docs, pull requests merged in 2019-11, with the labels that each got.

#24 Release note that the CCPs are gone. Adding KafkaChannel to KafkaDoc,…
  modules/ROOT/pages/proc_apache-kafka.adoc
  modules/ROOT/pages/proc_knative-eventing.adoc
Labels: size/S

#25 Updated build to include changes from dev
  docs/_images/kafka-configmap.png
  docs/proc_apache-kafka.html
  docs/proc_knative-eventing.html
  sitemap.xml
Labels: size/M

#26 Add a warning for SMMR
  modules/ROOT/pages/proc_knative-eventing.adoc
Labels: size/XS

#27 Remove SMMR warning: We did land the actual fix now
  modules/ROOT/pages/proc_knative-eventing.adoc
Labels: size/XS
